Feature/implement disc function
formulajs/formulajs pull request #136
Opened 2023-01-04 03:22 UTC by aflorzy

Implements nearly all of DISC function.

Calculates correctly when using day count bases Actual/Actual, Actual/360, and Actual/365.

US (NASD) 30/360 and European 30/360 day count bases are not yet implemented. The function seems to be calculated more complexly using these two than when compared to the other three. More specifically, the `basisVal` used is not always an integer like the other three (360 or 365)

Meaningful errors are returned according to [Excel documentation](https://support.microsoft.com/en-us/office/disc-function-71fce9f3-3f05-4acf-a5a3-eac6ef4daa53) when invalid arguments are passed.

Tests are implemented for each valid/invalid case. The cases utilizing the 30/360 day count bases are commented out until their implementation is complete.

I originally tried to throw an error if the invalid bases were used, but I couldn't figure out how to catch it in the test. I defaulted with throwing `error.num`. These errors are also commented out in case that is a better solution than returning `error.num`.

2023-01-06 22:37 UTC, nicolashefti requested changes
Thanks @aflorzy for the PR. Good work. There are small details to correct. You can add more meaning to the test cases for later extension of the function.

2023-01-06 22:37 UTC, nicolashefti commented on test/financial.js
>    it('DISC', () => {
Can you group assertions in a meaningfull way (see tests for TEXT, SUBSTITUE, VALUE) with a first level of `describe` ?

2023-01-06 22:37 UTC, nicolashefti commented on src/financial.js
> +   *
Maybe warn here about limitated implementation ?

2023-01-06 22:37 UTC, nicolashefti commented on src/financial.js
> +      // throw new Error('European 30/360 day count convention is not yet implemented')
Could be tested with Chai: https://www.chaijs.com/api/bdd/#method_throw

2023-01-06 22:37 UTC, nicolashefti commented on src/financial.js
> +      return error.num
Can you remove the lines 520 > 522?

2023-01-06 22:37 UTC, nicolashefti commented on src/financial.js
> +    // Return error if price is less than or equal to zero
This comment does not bring much given line 510 is easy to understand.

2023-01-06 22:37 UTC, nicolashefti commented on src/financial.js
> +    // Return error if redemption is less than or equal to zero
Same here

2023-01-07 23:10 UTC, aflorzy commented on src/financial.js
> +   *
Added a simple warning. Can change the format if a different way is preferred

2023-01-07 23:12 UTC, aflorzy commented on test/financial.js
>    it('DISC', () => {
Changed the format of the tests and removed some that were redundant

2023-01-07 23:12 UTC, aflorzy commented on src/financial.js
> +      // throw new Error('European 30/360 day count convention is not yet implemented')
Got this to work now. Thank you for the link

2023-01-09 04:40 UTC, aflorzy commented
Function should be fully implemented at this point. Found that date subtraction uses DAYS360 for 30/360 day count conventions instead of DATEDIF so I was able to get the function to calculate properly using basis values 0 and 4.

2023-01-11 14:34 UTC, nicolashefti requested changes
Nice refactoring of the function and test cases. Some minor details to be addressed. Thanks!

2023-01-13 14:21 UTC, aflorzy commented
Thanks for reviewing! I have made the requested changes. Same story with #137

2023-01-13 16:38 UTC, nicolashefti approved these changes
Perfect ! Thank you.

2023-01-13 16:39 UTC, merged