Implement COUPDAYS
formulajs/formulajs pull request #156
Opened 2023-07-15 10:01 UTC by natanhp

## Description

Implement COUPDAYS function.

## Motivation and Context

This change will enable user to use COUPDAYS function from this library.

## How Has This Been Tested?

I tested it using the unit test, using screnario from [Microsoft Office COUPDAYS Official Documentation](https://support.microsoft.com/en-us/office/coupdays-function-cc64380b-315b-4e7b-950c-b30b0a76f671) and I cross checked it with Libre Office Calculator.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2023-07-19 09:08 UTC, nicolashefti commented
Hi @natanhp, thanks for your contribution. I'm on vacations and will check that next week.

2023-07-30 18:12 UTC, nicolashefti requested changes
Thanks for your contribution. I'm not an Excel/financial functions expert, but I feel there is something wrong between the if and the switch statements. Let me know if I missed something.

2023-07-30 18:12 UTC, nicolashefti commented on src/financial.js
> +    settlement = utils.parseDate(settlement)
Parameter checks (line 196 >> 206) could run for all basis values, no?

2023-07-30 18:12 UTC, nicolashefti commented on src/financial.js
> +    case 1:
Case 1 won't reach this line because of the if statement line 195 with return

2023-07-30 18:12 UTC, nicolashefti commented on src/financial.js
> +    case 3:
Case 3 same as case 1 ? In this case why would it be different than the if statement above?

2023-07-30 18:12 UTC, nicolashefti commented on src/financial.js
> +function lastCoupDateBeforeSettlement(settlement, maturity, frequency) {
This is the core part of the COUPDAYS function. It won't be reused anywhere, so I would include this part in the function itself.

2023-07-30 23:49 UTC, natanhp commented on src/financial.js
> +function lastCoupDateBeforeSettlement(settlement, maturity, frequency) {
Actually it can be used for any other functions such as COUPPCD

2023-07-30 23:50 UTC, natanhp commented on src/financial.js
> +    case 3:
My bad, I should remove case 1 because it's already handled by the if statement in the line 195

2023-08-01 19:37 UTC, nicolashefti approved these changes
Thanks for the changes. It's good for me.

2023-08-01 19:38 UTC, merged