Fix ISEVEN, ISODD and LEN
formulajs/formulajs pull request #31
Opened 2021-02-12 15:50 UTC by nikazooz

- ISEVEN and ISODD should return error if provided value is not a numeric.
- Since LEN handles arrays, I've added handling of empty array. Also, having `null` as (blank) input should return 0.
- Added some assertions for ISTEXT and ISLOGICAL

Let me know what you think about this.

Cheers!

2021-02-24 18:52 UTC, nicolashefti commented
@nikazooz I am just wondering if the current implementation of LEN is correct. Normally it should only accept a String as argument. All the rest should trigger an error.value.

https://exceljet.net/excel-functions/excel-len-function

2021-02-24 18:55 UTC, nicolashefti commented on test/information.js
> +    information.ISEVEN(null).should.equal(error.error);
It is missing a bit of consistence between ISEVEN, ISODD, ISLOGICAL on the null case. I would always return a boolean value in all 3 functions.

2021-02-25 20:17 UTC, nikazooz commented on test/information.js
> +    information.ISEVEN(null).should.equal(error.error);
In that case, what I did is incorrect

2021-02-25 20:23 UTC, nikazooz commented
@nicolashefti For LEN, the main reason is that when a reference to empty cell is used LEN returns 0. One could argue that empty cell still has an empty string but to me it made sense for it to handle `null` the same way. Does it make sense?

2021-02-26 20:53 UTC, nicolashefti requested changes

2021-02-26 20:53 UTC, nicolashefti commented on test/information.js
> +    information.ISEVEN(null).should.equal(error.error);
Can you update to return "false" in case of "null" for the 3 functions ?

2021-02-26 20:53 UTC, nicolashefti commented on test/text.js
> +    text.LEN([]).should.equal(0);
Can you remove the Array support as input ? I think this is a mistake of the early implementation.

text.LEN([1, 2, 3, 4, 5]).should.equal(error.error);
text.LEN([]).should.equal(error.error);

About edge cases, I would go for:

text.LEN('').should.equal(0);
text.LEN(null).should.equal(0);

2021-02-27 06:47 UTC, nikazooz commented on test/information.js
> +    information.ISEVEN(null).should.equal(error.error);
Should `ISEVEN` return `false` or `true? Currently, it returns true and Google Spreadsheets do the same. Don't know about Excel

2021-02-27 09:38 UTC, nicolashefti commented on test/information.js
> +    information.ISEVEN(null).should.equal(error.error);
Indeed, ISEVEN returns of empty cells returns TRUE (just tested in Excel).

2021-02-27 12:40 UTC, nikazooz commented
@nicolashefti I've made the changes

2021-02-27 13:24 UTC, nicolashefti approved these changes

2021-02-27 13:25 UTC, merged