[lib/math-trig] Fix null undefined na parity with excel for math trig
formulajs/formulajs pull request #53
Opened 2021-06-30 14:38 UTC by pbadenski

I simplified error checking to remove all or at least most of the duplication.

2021-06-30 14:39 UTC, pbadenski commented on lib/math-trig.js
> +  if (text === undefined || text === null) {
From @nicolashefti (orig: https://github.com/formulajs/formulajs/pull/51/files#r659165805):

utils.parseNumber?

2021-06-30 14:42 UTC, pbadenski commented on lib/math-trig.js
> +  if (text === undefined || text === null) {
This check looks similar to the first 2 checks in parseNumber, but otherwise it isn't. Input to ARABIC is a roman numeral so it is text. Personally I'd leave it as is - as an exception.

2021-06-30 14:42 UTC, pbadenski commented on lib/math-trig.js
> +  if (flatArguments.every(function (arg) { return arg === undefined || arg === null; })) {
From @nicolashefti (orig: https://github.com/formulajs/formulajs/pull/51/files#r659166060)

Can be checked in the existing loop

2021-06-30 15:04 UTC, pbadenski commented on lib/math-trig.js
> +  var flatArgumentsDefined = flatArguments.filter(function (arg) { return arg !== undefined && arg !== null; });
FYI this can't be pulled into the loop as the behaviour of PRODUCT(undefined, 1) is different to PRODUCT(0, 1). parseNumber converts undefined to 1, so check for undefined needs to occur before conversion.

2021-06-30 15:07 UTC, pbadenski commented
FYI:

 - first commit is the same as original changes (unless I made some silly mistake)
 - 980e125 and 6d21a4d - focus mostly on refactoring suggested in a previous pull request to simplify error handling
 - other commits are modifications to original pull request that I spotted during this rework. I tried to split them into smaller pieces of work and make commit messages explain the scope.
 - specifically I added a GT operator implementation which seemed to have been missing

2021-06-30 15:24 UTC, pbadenski commented on lib/math-trig.js
> +  if (flatArguments.every(function (arg) { return arg === undefined || arg === null; })) {
I removed this code in f827805

2021-07-02 15:10 UTC, nicolashefti commented
@pbadenski that's the heavy one with math-trig.js :) I will start the review this weekend.

2021-07-02 15:16 UTC, pbadenski commented
I understand that! :D Thank you.

2021-07-13 12:42 UTC, nicolashefti commented
@pbadenski, no I don't mind :) thanks for the reminder. Summer, holidays, kids, ... too much good excuses. I'll work on that til the end of the week. Sorry about the delay.

2021-07-19 08:14 UTC, nicolashefti requested changes
@pbadenski thanks for the in-depth corner case research and fix. I like the new anyError helper. Can you just add a few test cases for the 2 new helpers?

2021-07-19 08:14 UTC, nicolashefti commented on lib/utils/common.js
> +  var n = arguments.length;
Can you test this helper?

2021-07-19 08:14 UTC, nicolashefti commented on lib/utils/common.js
> +exports.anyIsString = function() {
Can you test this helper?

2021-07-19 08:14 UTC, nicolashefti commented on lib/math-trig.js
> +  if (text === undefined || text === null) {
Good for me

2021-07-19 16:16 UTC, pbadenski commented on lib/utils/common.js
> +exports.anyIsString = function() {
Done in e5d5967

2021-07-19 16:16 UTC, pbadenski commented on lib/utils/common.js
> +  var n = arguments.length;
Done in e5d5967 - good catch, implementation was subtly wrong

2021-07-21 19:20 UTC, nicolashefti approved these changes

2021-07-21 19:23 UTC, merged