Fix SUM for array of errors
formulajs/formulajs pull request #57
Opened 2021-07-30 18:19 UTC by pbadenski

Fix SUM for array of errors + add test case for PRODUCT in array of errors scenario.

Fixes: #56

2021-08-01 12:30 UTC, nicolashefti requested changes

2021-08-01 12:30 UTC, nicolashefti commented on test/math-trig.js
> +    mathTrig.SUM([1], [2], [error.na]).should.equal(error.na);
@pbadenski can you check what happens in these cases : `SUM([1],  [error.na], [2])` or just `SUM(1,  error.na, 2)`? I think these cases return undefined (because of line 1119 instead of the expected error.

2021-08-02 14:43 UTC, pbadenski commented on test/math-trig.js
> +    mathTrig.SUM([1], [2], [error.na]).should.equal(error.na);
Functionally everything is fine, but there was a performance issue there, which I fixed.

Everything works fine - because once result "traps" the error it will not allow any more logic to kick in.

There was a performance issue, because it should `return false` instead - thus short circuiting the iteration.

2021-08-05 12:03 UTC, nicolashefti commented on test/math-trig.js
> +    mathTrig.SUM([1], [2], [error.na]).should.equal(error.na);
Perfect. Thank you for the explanation.

2021-08-05 12:03 UTC, nicolashefti approved these changes

2021-08-05 12:04 UTC, merged