Fix NETWORKDAYS.INTL rounding error
formulajs/formulajs pull request #66
Opened 2021-08-18 01:20 UTC by bornova

[PR #33](https://github.com/formulajs/formulajs/pull/33) introduced using a sting mask values to return number of days between two dates.  However, in some cases, the value returned is incorrect due to rounding errors on the days calculation.  For example:

`NETWORKDAYS.INTL('11/01/2021', '11/30/2021', "1110111")` returns 3.041666666666668 whereas the answer should be 4.

Line calculating the days is:
https://github.com/formulajs/formulajs/blob/4c2badf97ea6500e5c27fecfb53672ad208c8afd/lib/date-time.js#L384

To fixed this, I suggest we improve the day calculation by rounding the result as follows:
`var days = Math.round((end_date - start_date) / (1000 * 60 * 60 * 24)) + 1;`

2021-08-18 19:51 UTC, pbadenski commented
Can you add appropriate unit tests for this?

2021-08-23 18:49 UTC, nicolashefti requested changes
Thanks @bornova for the bug fix. A few minor changes, otherwise this looks good to me.

2021-08-23 18:49 UTC, nicolashefti commented on lib/date-time.js
> +      if (+weekend[i] === 1) {
To me, the more logicial version is to check `weekend[i] === "1"` instead of parsing to int with `+` to check against the numeric version.

2021-08-23 18:49 UTC, nicolashefti commented on test/date-time.js
> +    dateTime.NETWORKDAYS.INTL('11/01/2021', '11/30/2021', "1110111").should.equal(4);
Can you use simple quotes on the third arg?

2021-08-23 19:05 UTC, bornova commented on lib/date-time.js
> +      if (+weekend[i] === 1) {
Agreed. Thanks for the suggestion. I have made the change.

2021-08-23 19:05 UTC, bornova commented on test/date-time.js
> +    dateTime.NETWORKDAYS.INTL('11/01/2021', '11/30/2021', "1110111").should.equal(4);
Done.

2021-08-24 08:34 UTC, nicolashefti approved these changes

2021-08-24 08:34 UTC, merged