Fix parsing date from float serial number
formulajs/formulajs pull request #76
Opened 2021-11-16 00:43 UTC by jhkcia

Matching excel conversion for float numbers.
float part of a serial number shows time and it was ignored.

2021-11-16 21:58 UTC, nicolashefti commented
@jhkcia thanks for your contribution. I'll review it this weekend latest.

2021-11-21 19:12 UTC, jhkcia commented
> @jhkcia thanks for your contribution. I'll review it this weekend latest.

@nicolashefti did you check the PRs?

2021-11-22 10:48 UTC, nicolashefti requested changes
Can you add a few test cases for the parseDate function (string, Date)?

2021-11-22 10:48 UTC, nicolashefti commented on test/utils/common.js
> +    utils.parseDate(1).getTime().should.equal(new Date('1/1/1900').getTime());
I think most of these test cases address the serialNumberToDate function?

The scope of parseDate is a bit larger. It can manage Date Object, string, number, etc.

Can you create 2 sections of tests. One for each function ?

2021-11-22 14:16 UTC, jhkcia commented on test/utils/common.js
> +    // utils.parseDate('2009-07-01').getTime().should.equal(new Date(2009, 7-1, 1).getTime());
@nicolashefti I don't know why this test fails. I comment it.

2021-11-22 14:17 UTC, jhkcia commented on test/utils/common.js
> +    utils.parseDate(1).getTime().should.equal(new Date('1/1/1900').getTime());
Done!

2021-11-28 19:46 UTC, nicolashefti requested changes
Some minor refactoring and then we can merge. Sorry about my late reply. I'll try to be more reactive in the coming days!

2021-11-28 19:46 UTC, nicolashefti commented on test/utils/common.js
> +    utils.parseDate(1).getTime().should.equal(new Date('1/1/1900').getTime());
Last comment and then we can merge: can group all assertions about the function under one "describe". We started this in ./tests/text.js >> VALUE.

2021-11-28 19:46 UTC, nicolashefti commented on test/utils/common.js
> +    // utils.parseDate('2009-07-01').getTime().should.equal(new Date(2009, 7-1, 1).getTime());
Can you keep it in a "xit" statement (as reminder for later contributions)?

```
xit('should normally work', function(){
  ...
}
```

2021-11-29 12:29 UTC, jhkcia commented on test/utils/common.js
> +    // utils.parseDate('2009-07-01').getTime().should.equal(new Date(2009, 7-1, 1).getTime());
Done!

2021-11-29 12:29 UTC, jhkcia commented on test/utils/common.js
> +    utils.parseDate(1).getTime().should.equal(new Date('1/1/1900').getTime());
Good structure!
I refactored it.

2021-11-29 12:31 UTC, jhkcia reviewed
Done

2021-11-29 12:32 UTC, jhkcia reviewed
done

2021-11-29 13:57 UTC, nicolashefti approved these changes
@jhkcia thanks for your contribution. Nice work.

2021-11-29 13:57 UTC, merged

2022-01-05 20:12 UTC, nicolashefti commented
@jhkcia can you check #85 ? You wrote the serialNumberToDate function and it seems to work only on certain time zones.