Fix DATE function for negative parameters
formulajs/formulajs pull request #77
Opened 2021-11-16 00:47 UTC by jhkcia

On excel negative parameters of DATE function works and try to subtract the number from the date, now it matches excel.

2021-11-22 10:41 UTC, nicolashefti reviewed
Thanks for the fix and upgrade. I just have little questions.

2021-11-22 10:41 UTC, nicolashefti commented on test/date-time.js
> +    date.getFullYear().should.equal(1899);
I agree with this one, but with 1900, I get an error num. Just another mistery of Excel.

```
=DATE(1910; 1;-1) => 1909.12.30
=DATE(1900; 1;-1) => #NUM
```

2021-11-22 10:41 UTC, nicolashefti commented on test/date-time.js
> +    // dateTime.DATE(1899, 1, 1).getFullYear().should.equal(3799);
Another weird thing of Excel?

2021-11-22 10:41 UTC, nicolashefti commented on test/date-time.js
> +    date.getMonth().should.equal(12 - 1);
11 ? Why 12 - 1 ?

2021-11-22 10:41 UTC, nicolashefti commented on test/date-time.js
> -    date.getDay().should.equal(1);
Nicely spoted.

2021-11-22 20:58 UTC, jhkcia commented
@nicolashefti 
Excel minimum date is 1900/01/01, it does not support any date below that, so `=DATE(1900; 1;-1)`  is an invalid formula and if the year is lower than 1900 it tries to add it to 1900 so DateTime.DATE(1899, 1, 1).getFullYear().should.equal(3799)  is excel behaviour.

`11 ? Why 12 - 1 ?`
in JS month start from zero but in excel it starts from 1. so for assertions, I reduce 1 from the month number.

`date.getDay().should.equal(1);`
getDay return day of the week, I replaced it with getDate which returns the day number of a date.

2021-11-28 19:50 UTC, nicolashefti requested changes

2021-11-28 19:50 UTC, nicolashefti commented on test/date-time.js
> +    // dateTime.DATE(1899, 1, 1).getFullYear().should.equal(3799);
Same as in the other PR. Can you create a xit statement for this one ?
```
xit(‘should be Excel behaviour, but we do not want to recreate it’, function(){
  ...
}
```

2021-11-29 13:58 UTC, nicolashefti approved these changes

2021-11-29 13:59 UTC, merged