Update README.md
formulajs/formulajs pull request #92
Opened 2022-01-25 21:41 UTC by bornova

2022-01-27 19:46 UTC, nicolashefti commented
@bornova that looks good. I'm a bit under a heavy workload right now. I'll do my best to review it in the coming days. 

@pbadenski any thoughts of this one? That goes beyond what we thought in issue #58, but I believe for the better. What do you think?

2022-01-28 20:49 UTC, pbadenski commented
This looks amazing, incredible work @bornova. I love it!

2022-01-30 19:41 UTC, nicolashefti requested changes
Really good work. Just a few questions/comments about scripts and dev dependencies.

2022-01-30 19:41 UTC, nicolashefti commented on package.json
> +    "lint": "eslint ./",
Is eslint correctly setup? I tried to had a few spaces in one of the ./src file and got not error while running the command.

2022-01-30 19:41 UTC, nicolashefti commented on package.json
> +    "watch": "mocha --watch --parallel --reporter min"
"test-watch" ? to fit the convention of the two lines above?

2022-01-30 19:41 UTC, nicolashefti commented on .prettierrc
> +{
prettier is not part of the devDependencies?

2022-01-30 19:41 UTC, nicolashefti commented on package.json
> +    "build": "npm run lint && rollup -c",
Can you add a command to run prettier?

2022-01-30 19:51 UTC, nicolashefti commented on .github/workflows/unit-tests.yaml
> +      - run: npm ci
@bornova you removed the timezone dependency in the Github action settings (in comparison with the original Travis config). Is that working? Because some tests are TZ dependant. For exemple, running locally:

`env TZ='America/Los_Angeles' node_modules/.bin/mocha`

I get 2 errors. These errors should not be fixed in the PR, but it might be more secure to still set the TZ in the GH action. What do you think?

2022-01-31 04:40 UTC, bornova commented on .github/workflows/unit-tests.yaml
> +      - run: npm ci
The 2 tests indeed do fail on my local machine (I am near Los Angeles).  However all tests pass when run on GH Actions.  To make sure consistency across all machines, I have added:
```javascript
process.env.TZ = 'Europe/Amsterdam'
```
to test `index.js` to set the timezone before running the test files.

2022-01-31 04:40 UTC, bornova commented on package.json
> +    "build": "npm run lint && rollup -c",
Sure can! Please see updated package.json.  New build workflow is: `pretttier > eslint > test > build`

2022-01-31 04:40 UTC, bornova commented on .prettierrc
> +{
I wanted to make sure we all agreed `prettier` was the right formatting tool before I added as a dev-dependency.  It is now added.  Please see updated `package.json`.

2022-01-31 04:40 UTC, bornova commented on package.json
> +    "watch": "mocha --watch --parallel --reporter min"
I have renamed the script `test:watch` to match the newly added `lint:fix` and `prettier:fix` scripts.  Would this make more sense? We could go with `test-watch` instead if you insist.

2022-01-31 04:40 UTC, bornova commented on package.json
> +    "lint": "eslint ./",
If we agree `prettier` is the right tool for code formatting, then `prettier` would be able to take care of formatting issues such as extra spaces.  We could run `prettier` with `eslint` to check for mistakes before build.  Please see new `lint` and `prettier` scripts in `package.json`.  Please let me know if this is acceptable.

2022-01-31 14:58 UTC, nicolashefti commented on package.json
> +    "lint": "eslint ./",
I think prettier and eslint have complementary goals but sometimes they overlap a bit (on spacing rules for example). Let's keep both of them.

I normally run code-style checks along with the test task during PR. This way I ensure the quality of code merged into master.

2022-01-31 14:58 UTC, nicolashefti commented on package.json
> +    "watch": "mocha --watch --parallel --reporter min"
Good for me!

2022-01-31 15:45 UTC, nicolashefti commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
I would put all `npm run prettier && npm run lint && npm run test:coverage` in a `prebuild` task for the sake of clarity https://docs.npmjs.com/cli/v6/using-npm/scripts#pre--post-scripts

But I wonder if this is not too much given the GH Action with all these tasks would run for each PR.

2022-01-31 15:47 UTC, nicolashefti commented on .github/workflows/unit-tests.yaml
> +      - run: npm ci
Good for me. We should take care of this TZ dependency in the following weeks after V3 is released.

2022-01-31 15:50 UTC, nicolashefti commented on .github/workflows/unit-tests.yaml
> +      - run: npm test
We could also run code style and static check here:
```
- run: npm run lint
- run: npm run prettier
```

What do you think?

2022-01-31 16:31 UTC, bornova commented on package.json
> +    "lint": "eslint ./",
I included the `eslint-config-prettier` just for this purpose.  It takes care of the ovelapping rules.

I also now added the code-style checks and lint checks to `unit-tests` to ensure quality of code as you mentioned.  Thanks for the feedback!  Please let me know if there is anything else I may have missed.

2022-01-31 16:31 UTC, bornova commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
Since I have added the additional lint and prettier checks to `unit-tests` which runs on each pushed commit, this may be a bit redundant maybe?

2022-01-31 16:42 UTC, nicolashefti commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
I agree. Let's keep the build task simple in this case: `rollup -c`.

2022-01-31 17:26 UTC, bornova commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
On a second thought, if you are developing locally and run `npm run build` on your local machine, this woud bypass all code quality checks locally.  It is a bit redundant but I think we should keep all the checks in the build step for consistency between local and GitHub builds.  It only adds a few more seconds to the build time.  What do you think?

2022-01-31 19:22 UTC, nicolashefti commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
Indeed, we are speaking of a few milliseconds. No need to over-optimise things, we can keep quality checks. We can still change our mind if this is too much check while developing the library.

I would still go for a `prebuild` for quality checks and keep the `build` for the build it-self.

2022-01-31 19:44 UTC, bornova commented on package.json
> +    "build": "npm run prettier && npm run lint && npm run test:coverage && rollup -c",
Done. Added `prebuild` to package.json.  Thank you!

2022-02-01 10:41 UTC, nicolashefti commented
@bornova this looks ready for me. Very nice work here. @pbadenski do you want to add something?

2022-02-01 21:11 UTC, bornova commented
I have another code formatting suggestion/question:

I kept the top level function declarations as regular functions. Ex. `function xyz(args) { }` and `export function XYZ (args) { }` instead of using arrow functions which is more standard nowadays with ES6+.  For exported functions, it makes sense to keep it this way becasue a lot of these functions in this library depend on the `arguments` object, which doesn't exist in arrow functions.  However, for other top level functions which are not exported, this could change.  So what I am suggesting is:

If a function is exported, we keep regular function declarations.  For everything else, use arrow functions.

For example, in `database.js`, 
```javascript
function compact(array) {
  const result = []

  utils.arrayEach(array, (value) => {
    if (value) {
      result.push(value)
    }
  })

  return result
}
```
would become:
```javascript
const compact = (array) => {
  const result = []

  utils.arrayEach(array, (value) => {
    if (value) {
      result.push(value)
    }
  })

  return result
}
```
and
```javascript
export function FINDFIELD(database, title) { ... }
```
stays the same since it's an export function.  We would still keep the lowercase vs uppercase function naming convension.  I think this would help further standardize the code base, where we distinguish which functions are exported components of `formulajs` and which are just internal helper functions. What do you think?

2022-02-01 21:54 UTC, nicolashefti commented
> I have another code formatting suggestion/question:
> .., where we distinguish which functions are exported components of `formulajs` and which are just internal helper functions. What do you think?

I would like to merge this one first as it is then make the setup with Github actions and auto-deployment.

For me, the next task in the agenda is to solve the timezone dependency which is quite annoying.

Can you post this improvement in another issue where can discuss if it makes sense to do such refactoring?

2022-02-01 22:10 UTC, bornova commented
> I would like to merge this one first as it is then make the setup with Github actions and auto-deployment.
> 
> For me, the next task in the agenda is to solve the timezone dependency which is quite annoying.
> 
> Can you post this improvement in another issue where can discuss if it makes sense to do such refactoring?

No problem.  I should also note this PR includes PR https://github.com/formulajs/formulajs/pull/90, which implements `TEXTJOIN`

Would you like to keep it in this PR and close https://github.com/formulajs/formulajs/pull/90? or remove it from this PR and merge https://github.com/formulajs/formulajs/pull/90 later?

2022-02-02 20:09 UTC, nicolashefti commented
@bornova you can leave it like that with `TEXTJOIN` included. Thanks

2022-02-02 20:09 UTC, nicolashefti approved these changes

2022-02-02 20:09 UTC, merged